version: '2'
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 15672:15672
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    links:
      - config

  config:
    environment:
      CONFIG_SERVICE_PASSWORD: root
    image: goodraincloudframeworks/piggymetrics-config
    restart: always
    ports:
      - 8888:8888
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  registry:
    environment:
      CONFIG_SERVICE_PASSWORD: root
    image: goodraincloudframeworks/piggymetrics-registry
    links:
      - config
    restart: always
    ports:
      - 8761:8761
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  gateway:
    environment:
      CONFIG_SERVICE_PASSWORD: root
    image: goodraincloudframeworks/piggymetrics-gateway
    links:
      - registry
      - auth-service
      - config
    restart: always
    ports:
      - 4000:4000
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  auth-service:
    environment:
      CONFIG_SERVICE_PASSWORD: root
      NOTIFICATION_SERVICE_PASSWORD: root
      STATISTICS_SERVICE_PASSWORD: root
      ACCOUNT_SERVICE_PASSWORD: root
      MONGODB_PASSWORD: root
    image: goodraincloudframeworks/piggymetrics-auth-service
    links:
      - config
      - auth-mongodb
      - registry
    restart: always
    ports:
      - 5000:5000
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  auth-mongodb:
    environment:
      MONGODB_PASSWORD: root
    image: goodraincloudframeworks/piggymetrics-mongodb
    restart: always
    ports:
      - 27017:27017
    logging:
      options:
        max-size: "10m"
        max-file: "10"